name: Deploy to IONOS

on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: THE BOUNCER (Check the code)
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # STEP A: Install Python (The programming language)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # STEP B: Install the Validator Tool manually
      - name: Install HTML Validator
        run: pip install html5validator

      # STEP C: Run the Tool
      - name: Run HTML Validator
        run: html5validator --root . --ignore-re '.*node_modules.*'

  # JOB 2: THE DELIVERY (Only runs if Job 1 passes)
  deploy:
    needs: [check-code]
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      
      - name: Remove .git and .github folders
        run: rm -rf .git .github

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22 
          local_path: './'
          remote_path: '/public'
          sftp_only: true